"Differential Backup (2 Blocks Updated)": {
  "Block List": {
    DS0: {
      DB1: {
        style: {
          fill: darkblue
          font-color: white
        }
      }
      DB2: {
        style: {
          fill: darkblue
          font-color: white
        }
      }
    }
  }

  "Block Map": {
    FS0: {
      FB0: {
        style: {
          fill: darkgreen
          font-color: white
        }
      }
    }
    DS0: {
      DB1: {
        style: {
          fill: darkblue
          font-color: white
        }
      }
      DB2: {
        style: {
          fill: darkblue
          font-color: white
        }
      }
    }
    FS1: {
      FB3: {
        style: {
          fill: darkgreen
          font-color: white
        }
      }
    }
  }
}
