"Incremental Backup (2 Blocks Updated, 1 Block Added)": {
  "Block List": {
    IS0: {
      IB2: {
        style: {
          fill: darkcyan
          font-color: white
        }
      }
      IB3: {
        style: {
          fill: darkcyan
          font-color: white
        }
      }
    }
    IS1: {
      IB4: {
        style: {
          fill: darkcyan
          font-color: white
        }
      }
    }
  }

  "Block Map": {
    FS0: {
      FB0: {
        style: {
          fill: darkgreen
          font-color: white
        }
      }
    }
    DS0: {
      DB1: {
        style: {
          fill: darkblue
          font-color: white
        }
      }
    }
    IS0: {
      IB2: {
        style: {
          fill: darkcyan
          font-color: white
        }
      }
      IB3: {
        style: {
          fill: darkcyan
          font-color: white
        }
      }
    }
    IS1: {
      IB4: {
        style: {
          fill: darkcyan
          font-color: white
        }
      }
    }
  }
}
