"Bundle": {
  "File 1": {
    style: {
      fill: darkblue
      font-color: white
    }
  }

  "File 2": {
    style: {
      fill: darkgreen
      font-color: white
    }
  }

  "File 3": {
    style: {
      fill: darkblue
      font-color: white
    }
  }

  "File 4": {
    style: {
      fill: darkgreen
      font-color: white
    }
  }

  "...": {
    style: {
      fill: darkblue
      font-color: white
    }
  }
}
