Vagrant.configure(2) do |config|
    config.vm.box = "boxcutter/ubuntu1404"

    config.vm.provider :virtualbox do |vb|
        vb.name = "backrest-demo-ubuntu-14.04"
    end

    # Provision the VM
    config.vm.provision "shell", inline: <<-SHELL
        # Install db
        echo 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5' >> /etc/apt/sources.list.d/pgdg.list
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        apt-get install -y postgresql-9.4
        pg_dropcluster --stop 9.4 main

        # Install pgBackRest
        wget -q -O - https://github.com/pgmasters/backrest/archive/release/0.85.tar.gz | tar zxv -C ~
        cp -r ~/backrest-release-0.85/lib/BackRest /usr/lib/perl5
        find /usr/lib/perl5/BackRest -type f -exec chmod 644 {} +
        find /usr/lib/perl5/BackRest -type d -exec chmod 755 {} +
        cp ~/backrest-release-0.85/bin/pg_backrest /usr/bin/pg_backrest
        chmod 755 /usr/bin/pg_backrest

        # Make default log directory writable to vagrant
        mkdir /var/run/postgresql
        chmod 777 /var/run/postgresql
        touch /etc/pg_backrest.conf
        chown vagrant:vagrant /etc/pg_backrest.conf

        # Install required Perl modules
        apt-get -y --force-yes install libdbd-pg-perl libdbi-perl libnet-daemon-perl libplrpc-perl libterm-readkey-perl
    SHELL

  # Don't share the default vagrant folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Mount demo path for testing
  config.vm.synced_folder ".", "/demo"
end
